export const PUDUKOTTAI_PLACES = [
  'Pudukottai', 'Aranthangi', 'Alangudi', 'Keeranur', 'Thirumayam',
  'Karambakudi', 'Ponnamaravathi', 'Viralimalai', 'Gandarvakottai',
  'Illuppur', 'Manamelkudi', 'Avudaiyarkoil', 'Kulipirai', 'Annavasal',
  'Mimisal', 'Peravurani', 'Thanjavur', 'Trichy', 'Madurai', 'Chennai',
];

export const questions = [
  {
    id: 'gender',
    tamil: 'நீங்கள் ஆண் அல்லது பெண்?',
    english: 'What is your gender?',
    icon: '/assets/emojis/person.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'male', label: 'ஆண் (Male)', img: '/assets/emojis/man.png' },
      { value: 'female', label: 'பெண் (Female)', img: '/assets/emojis/woman.png' },
      { value: 'other', label: 'மற்றவை (Other)', img: '/assets/emojis/person.png' },
    ],
  },
  {
    id: 'age',
    tamil: 'உங்கள் வயது என்ன?',
    english: 'What is your age?',
    icon: '/assets/emojis/birthday_cake.png',
    type: 'radio',
    required: true,
    options: [
      { value: '15-25', label: '15 – 25' },
      { value: '26-40', label: '26 – 40' },
      { value: '40-60', label: '40 – 60' },
      { value: '60+',   label: '60+' },
    ],
  },
  {
    id: 'location',
    tamil: 'நீங்கள் எந்த ஊரில் வசிக்கிறீர்கள்?',
    english: 'Which place do you live in?',
    icon: '/assets/emojis/round_pushpin.png',
    type: 'location',
    required: true,
  },
  {
    id: 'areaType',
    tamil: 'உங்கள் பகுதி எப்படி உள்ளது?',
    english: 'What type of area do you live in?',
    icon: '/assets/emojis/house_with_garden.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'village', label: 'கிராமம் (Village)', img: '/assets/emojis/sheaf_of_rice.png' },
      { value: 'town', label: 'நகரம் (Town)', img: '/assets/emojis/houses.png' },
      { value: 'city', label: 'மாநகர் (City)', img: '/assets/emojis/cityscape.png' },
    ],
  },
  {
    id: 'occupation',
    tamil: 'நீங்கள் என்ன வேலை செய்கிறீர்கள்?',
    english: 'What is your occupation?',
    icon: '/assets/emojis/briefcase.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'farming', label: 'விவசாயம் (Farming)', img: '/assets/emojis/sheaf_of_rice.png' },
      { value: 'labour', label: 'வேலைக்காரர் (Labour)', img: '/assets/emojis/hammer.png' },
      { value: 'business', label: 'தொழில் (Business)', img: '/assets/emojis/convenience_store.png' },
      { value: 'student', label: 'மாணவர் (Student)', img: '/assets/emojis/books.png' },
      { value: 'homemaker', label: 'வீட்டு வேலை (Homemaker)', img: '/assets/emojis/house.png' },
    ],
  },
  {
    id: 'income',
    tamil: 'உங்கள் மாத வருமானம் எவ்வளவு?',
    english: 'What is your monthly income?',
    icon: '/assets/emojis/money_bag.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'below_5k',    label: '₹5,000 கீழே (Below ₹5k)' },
      { value: '5k_15k',      label: '₹5,000 – ₹15,000' },
      { value: '15k_30k',     label: '₹15,000 – ₹30,000' },
      { value: 'above_30k',   label: '₹30,000+ மேலே' },
    ],
  },
  {
    id: 'buyItems',
    tamil: 'நீங்கள் அதிகமாக வாங்கும் பொருட்கள் என்ன?',
    english: 'What do you buy most often?',
    icon: '/assets/emojis/shopping_bags.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'vegetables', label: 'காய்கறி / பழங்கள்', img: '/assets/emojis/broccoli.png' },
      { value: 'groceries', label: 'உணவு பொருட்கள்', img: '/assets/emojis/bento_box.png' },
      { value: 'household', label: 'வீட்டு பொருட்கள்', img: '/assets/emojis/house.png' },
      { value: 'agriculture', label: 'விவசாய பொருட்கள்', img: '/assets/emojis/sheaf_of_rice.png' },
    ],
  },
  {
    id: 'buySource',
    tamil: 'நீங்கள் எங்கிருந்து வாங்குகிறீர்கள்?',
    english: 'Where do you usually buy?',
    icon: '/assets/emojis/convenience_store.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'nearby_shop', label: 'அருகிலுள்ள கடை (Nearby Shop)', img: '/assets/emojis/department_store.png' },
      { value: 'market', label: 'சந்தை (Market)', img: '/assets/emojis/shopping_cart.png' },
      { value: 'street_vendor', label: 'தெரு விற்பவர் (Street Vendor)', img: '/assets/emojis/person_walking.png' },
      { value: 'online', label: 'ஆன்லைன் (Online)', img: '/assets/emojis/package.png' },
    ],
  },
  {
    id: 'buyingProblems',
    tamil: 'வாங்கும்போது நீங்கள் சந்திக்கும் பிரச்சனை என்ன?',
    english: 'What problem do you face while buying?',
    icon: '/assets/emojis/warning.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'high_price', label: 'விலை அதிகம் (High Price)', img: '/assets/emojis/money_with_wings.png' },
      { value: 'low_quality', label: 'தரம் குறைவு (Low Quality)', img: '/assets/emojis/disappointed_face.png' },
      { value: 'not_nearby', label: 'அருகில் கிடைக்கவில்லை (Not Nearby)', img: '/assets/emojis/round_pushpin.png' },
      { value: 'less_choice', label: 'தேர்வு குறைவு (Less Choice)', img: '/assets/emojis/person_shrugging.png' },
    ],
  },
  {
    id: 'missingProducts',
    tamil: 'உங்கள் ஊரில் கிடைக்காத பொருட்கள் என்ன?',
    english: 'What products are missing in your area?',
    icon: '/assets/emojis/magnifying_glass.png',
    type: 'radio-other',
    required: true,
    options: [
      { value: 'quality_veg', label: 'நல்ல தரமான காய்கறி', img: '/assets/emojis/broccoli.png' },
      { value: 'home_food', label: 'வீட்டில் செய்த உணவு', img: '/assets/emojis/bento_box.png' },
      { value: 'cheap_goods', label: 'மலிவான பொருட்கள்', img: '/assets/emojis/money_bag.png' },
      { value: 'agri_products', label: 'விவசாய பொருட்கள்', img: '/assets/emojis/sheaf_of_rice.png' },
    ],
  },
  {
    id: 'wantsToSell',
    tamil: 'நீங்கள் ஏதாவது விற்க விரும்புகிறீர்களா?',
    english: 'Do you want to sell something?',
    icon: '/assets/emojis/label.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'yes', label: 'ஆம் (Yes)', img: '/assets/emojis/check_mark_button.png' },
      { value: 'no', label: 'இல்லை (No)', img: '/assets/emojis/cross_mark.png' },
    ],
  },
  {
    id: 'sellItems',
    tamil: 'நீங்கள் என்ன விற்க முடியும்?',
    english: 'What can you sell?',
    icon: '/assets/emojis/ear_of_corn.png',
    type: 'radio',
    required: false,
    showIf: { id: 'wantsToSell', value: 'yes' },
    options: [
      { value: 'vegetables', label: 'காய்கறி / பழங்கள்', img: '/assets/emojis/broccoli.png' },
      { value: 'homefood', label: 'வீட்டில் செய்த உணவு', img: '/assets/emojis/bento_box.png' },
      { value: 'milk_eggs', label: 'பால் / முட்டை', img: '/assets/emojis/glass_of_milk.png' },
      { value: 'handicrafts', label: 'கைத்தொழில் பொருட்கள்', img: '/assets/emojis/thread.png' },
    ],
  },
  {
    id: 'sellingProblems',
    tamil: 'நீங்கள் விற்கும்போது சந்திக்கும் பிரச்சனை என்ன?',
    english: 'What problem do you face while selling?',
    icon: '/assets/emojis/chart_decreasing.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'no_customers', label: 'வாடிக்கையாளர் இல்லை (No Customers)', img: '/assets/emojis/busts_in_silhouette.png' },
      { value: 'low_price', label: 'குறைந்த விலை (Low Price)', img: '/assets/emojis/money_with_wings.png' },
      { value: 'transport', label: 'போக்குவரத்து சிக்கல் (Transport)', img: '/assets/emojis/automobile.png' },
      { value: 'no_market', label: 'மார்க்கெட் தெரியவில்லை (No Market Info)', img: '/assets/emojis/world_map.png' },
    ],
  },
  {
    id: 'services',
    tamil: 'உங்களுக்கு எந்த சேவை தேவை?',
    english: 'What services do you need often?',
    icon: '/assets/emojis/wrench.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'electrician', label: 'Electrician', img: '/assets/emojis/high_voltage.png' },
      { value: 'plumber', label: 'Plumber', img: '/assets/emojis/wrench.png' },
      { value: 'carpenter', label: 'Carpenter', img: '/assets/emojis/carpenter_saw.png' },
      { value: 'mechanic', label: 'Mechanic', img: '/assets/emojis/nut_and_bolt.png' },
    ],
  },
  {
    id: 'phoneUsage',
    tamil: 'நீங்கள் மொபைல் எப்படி பயன்படுத்துகிறீர்கள்?',
    english: 'How do you use your phone?',
    icon: '/assets/emojis/mobile_phone.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'call_only', label: 'Call மட்டும் (Call Only)', img: '/assets/emojis/telephone_receiver.png' },
      { value: 'whatsapp', label: 'WhatsApp', img: '/assets/emojis/speech_balloon.png' },
      { value: 'internet', label: 'Internet', img: '/assets/emojis/globe_with_meridians.png' },
    ],
  },
  {
    id: 'buyingPreference',
    tamil: 'நீங்கள் எப்படி வாங்க விரும்புகிறீர்கள்?',
    english: 'How do you prefer buying?',
    icon: '/assets/emojis/shopping_cart.png',
    type: 'radio',
    required: true,
    options: [
      { value: 'in_person', label: 'நேரில் (In Person)', img: '/assets/emojis/convenience_store.png' },
      { value: 'phone_call', label: 'Phone Call', img: '/assets/emojis/telephone_receiver.png' },
      { value: 'whatsapp', label: 'WhatsApp', img: '/assets/emojis/speech_balloon.png' },
    ],
  },
  {
    id: 'suggestion',
    tamil: 'உங்கள் ஊரில் எந்த business இருந்தால் நல்லது?',
    english: 'What business would be useful in your area?',
    icon: '/assets/emojis/light_bulb.png',
    type: 'text',
    required: false,
    placeholder: 'உங்கள் கருத்தை இங்கே எழுதுங்கள்... (Write your idea here...)',
  },
];
